spring.application.name=notub

server.forward-headers-strategy=NATIVE

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

projetoea.app.jwtSecret=${JWT_SECRET}
projetoea.app.jwtExpirationMs=86400000

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:default}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:default}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

notub.rabbitmq.exchange=${RABBITMQ_EXCHANGE}
notub.rabbitmq.fila=${RABBITMQ_FILA}
notub.rabbitmq.routing-key.utilizador-criado=${RABBITMQ_RK_UTILIZADOR_CRIADO}
notub.rabbitmq.routing-key.recuperacao-password=${RABBITMQ_RK_RECUPERACAO_PASSWORD}

notub.stripe.secret-key=${STRIPE_SECRET_KEY}
notub.stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY}

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
logging.level.org.springframework.security.oauth2=DEBUG

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


# # Show SQL
# spring.jpa.show-sql=true

# # Format SQL nicely
# spring.jpa.properties.hibernate.format_sql=true

# # Show parameter values
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=TRACE