spring.application.name=servico-email

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:notub}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:notub123}

notub.rabbitmq.exchange=${RABBITMQ_EXCHANGE:notub.email.exchange}
notub.rabbitmq.fila=${RABBITMQ_FILA:notub.email.fila}
notub.rabbitmq.routing-key.utilizador-criado=${RABBITMQ_RK_UTILIZADOR_CRIADO:UTILIZADOR_CRIADO}
notub.rabbitmq.routing-key.recuperacao-password=${RABBITMQ_RK_RECUPERACAO_PASSWORD:RECUPERACAO_PASSWORD_PEDIDA}

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
