spring.application.name=servico-email

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

notub.rabbitmq.exchange=${RABBITMQ_EXCHANGE}
notub.rabbitmq.fila=${RABBITMQ_FILA}
notub.rabbitmq.routing-key.utilizador-criado=${RABBITMQ_RK_UTILIZADOR_CRIADO}
notub.rabbitmq.routing-key.recuperacao-password=${RABBITMQ_RK_RECUPERACAO_PASSWORD}

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=${MAILTRAP_PORT}
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notub.frontend.url=${FRONTEND_URL}